server:
  port: 8099

#spring:
#  config:
#    activate:
#      on-profile: dev
#spring:
#  profiles:
#    active: qa

#management:
#  endspoints:
#    web:
#      exposure:
#        include: "*"

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: Tushar@123
#    url: jdbc:mysql://localhost:3306/utemployeedb
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true

#spring:
#  profiles: qa
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: Tushar@123
#    url: jdbc:mysql://localhost:3306/utemployeedb-qa
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#
#
#---
#
#spring:
#  profiles: prod
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: Tushar@123
#    url: jdbc:mysql://localhost:3306/utemployeedb-prod
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
